---
swagger: "2.0"
info:
  description: "Swagger server for demonstration"
  version: "1.0"
  title: "Sridhars server"
basePath: "/sridharapi/v1"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /sayhello:
    get:
      tags:
      - "Tenant"
      description: "Say Hello!"
      operationId: "sridhar_say_hello"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"
      x-swagger-router-controller: "controllers.hello_world"
